#!/usr/bin/env bash
read -p "Press ENTER to continue"

./remove-legacy

rm -rf ./account-generator
rm -rf ./build
rm -rf ./cathook
rm -rf ./voidhook-ipc-server
rm -rf ./cathook-ipc-web-panel
rm -rf ./just-disable-vac
rm -rf ./user_instances
rm -rf ./catbot-database
sudo rm -rf /opt/voidhook/ipc
sudo rm /opt/voidhook/bin/libcathook-textmode.so
